config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :maraudes, only: [:index, :show, :create, :new] do
    resources :bookings, only:  [:new, :create]
  end

  get "dashboard", to: "pages#dashboard"
  # get "mycurrentbookings", to: "pages#mycurrentbookings"
  # get "mypastbookings", to: "pages#mypastbookings"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asso.rb
class Asso < ApplicationRecord
  belongs_to :user
  has_many :maraudes
  mount_uploader :photo, PhotoUploader
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :maraude
  belongs_to :user

  after_save :check_status

  def check_status
    if self.maraude.capacity.to_i - self.maraude.bookings.size == 0
      self.maraude.update(status: "full")
    end
  end
end

app/models/maraude.rb
class Maraude < ApplicationRecord
  belongs_to :asso
  has_many :bookings, dependent: :destroy
  geocoded_by :address_start, latitude: :ltd_starts, longitude: :lng_starts
  after_validation :geocode, if: :will_save_change_to_address_start?
  after_validation :geocode_address_end, if: :will_save_change_to_address_end?
  after_validation :direction_json, if: :will_save_change_to_address_end? || :will_save_change_to_address_start?
  mount_uploader :photo, PhotoUploader

  def remaining_places
    self.capacity.to_i - self.bookings.size
  end

  private

  def geocode_address_end
    coordinates = Geocoder.search(address_end).first.coordinates
    self.ltd_ends = coordinates[0]
    self.lng_ends = coordinates[1]
  end

  def direction_json
    self.direction = JSON.parse(HTTP.get("https://api.mapbox.com/directions/v5/mapbox/walking/#{self.lng_starts},#{self.ltd_starts};#{self.lng_ends},#{self.ltd_ends}?steps=true&access_token=#{ENV['MAPBOX_API_KEY']}").body)
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings

  has_many :assos
  has_many :maraudes, through: :assos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
  { host: ENV['DOMAIN'] || "localhost:3000" }
  end

end

app/controllers/assos_controller.rb
class AssosController < ApplicationController
def create

end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_maraude, only: [:new, :create]
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @booking.user = current_user
    @booking.maraude = @maraude
    # current_user.update(user_params)
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def set_maraude
    @maraude = Maraude.find(params[:maraude_id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number)
  end


end

app/controllers/maraudes_controller.rb
class MaraudesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @maraudes = Maraude.near(params[:query], 0.5).where("starts_at > ?", Date.today).reject{ |m| current_user.bookings.where(maraude: m).exists? if user_signed_in? }
      actual_position = params[:query]
      coordinates = Geocoder.search(actual_position).first.data
      @markers_actual_position = {
        lat: coordinates["lat"],
        lng: coordinates["lon"]
        # infoWindow: render_to_string(partial: "info_window", locals: { maraude: maraude })
      }
    else
      @maraudes = Maraude.geocoded.where("starts_at > ?", Date.today).reject{ |m| current_user.bookings.where(maraude: m).exists? if user_signed_in? }
    end

    @markers = @maraudes.map do |maraude|
      {
        lat_starts: maraude.ltd_starts,
        lng_starts: maraude.lng_starts,
        lat_ends: maraude.ltd_ends,
        lng_ends: maraude.lng_ends,
        infoWindow: render_to_string(partial: "info_window", locals: { maraude: maraude }),
        image_starts_url: helpers.asset_url('pin_starts.png'),
        image_ends_url: helpers.asset_url('pin_ends.png'),
        steps: maraude.direction["routes"].first["legs"].first["steps"],
        maraude_id: maraude.id
      }
    end
  end

  def show
    @maraude = Maraude.find(params[:id])
    @booking = Booking.new
    @maraudes = Maraude.geocoded #returns flats with coordinates
    @remaining_places = @maraude.remaining_places
    @markers = {
      lat_starts: @maraude.ltd_starts,
      lng_starts: @maraude.lng_starts,
      lat_ends: @maraude.ltd_ends,
      lng_ends: @maraude.lng_ends,
      infoWindow: render_to_string(partial: "info_window", locals: { maraude: @maraude }),
      image_starts_url: helpers.asset_url('pin_starts.png'),
      image_ends_url: helpers.asset_url('pin_ends.png')
    }
    direction = @maraude.direction
    @steps = direction["routes"].first["legs"].first["steps"]
  end

  def new
    @maraude = Maraude.new
  end

  def create
    @maraude = Maraude.new(maraude_params)
    @maraude.asso = current_user.assos.first
    if @maraude.save
      respond_to do |format|
        format.html { redirect_to maraude_path(@restaurant) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'maraudes/new' }
        format.js  # <-- idem
      end
    end
  end

  private

  def maraude_params
    params.require(:maraude).permit(:title, :address_start, :description, :capacity, :photo, :address_end, :starts_at, :ends_at)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @maraudes = Maraude.last(6)
    render layout: "home"
  end

  def dashboard
    @past_bookings = current_user.bookings.select { |booking| booking.maraude.ends_at < Date.today }
    @current_bookings = current_user.bookings.order(created_at: :desc).select { |booking| booking.maraude.ends_at > Date.today }


    @asso = current_user.assos.first
    @maraudes_as_owner = current_user.maraudes.order(created_at: :desc)

    #current_user.bookings.first.maraude.asso_id => l'id de l'asso par rapport au user
    render layout: "dashboard"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_of_days(start_date, end_date)
    ((end_date - start_date) / (60 * 60 * 24)).to_i
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/assos/association.html.erb
<h1>creation d'assos</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= favicon_link_tag 'alveole.png' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all' %><!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <div class="content">
      <%= yield %>
    </div>


    <%= render 'shared/footer' %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ALVEOLE - Le site de mise en relation de maraudes</title>
    <%= favicon_link_tag 'alveole.png' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all' %><!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/flashes' %>
    <div class="content-dashboard">

      <%= yield %>

    </div>


    <!-- <%#= render 'shared/footer' %> -->
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/maraudes/_info_window.html.erb
<h2><%= maraude.title %></h2>
<p><%= maraude.address_start %></p>

app/views/maraudes/create.js.erb
sideNav = document.querySelector(".sidenav");
sideNavRight = document.querySelector(".sidenav-right-part");
sideNavRight.classList.remove("sidenav-transition");
sideNav.classList.add("d-none");

lastCard = document.querySelector(".maraude-dashboard");
lastCard.insertAdjacentHTML('beforebegin', '<%= j render "maraudes/card_maraude_dashboard", maraude: @maraude %>');

inputs = document.querySelectorAll("input");
inputs.forEach((input) => {
  input.value = "";
})

app/views/maraudes/index.html.erb
<div class= "container container-index">
  <div class="index-content">
    <div class="index-left-part pr-2">
      <div class="searchbar-index">
        <%= form_tag maraudes_path, class: "form-flex", method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control autocomplete", placeholder: "Trouvez une Maraude..."%>
        <%= submit_tag "Recherche", class: "btn btn-warning" %>
        <% end %>
      </div>

      <div class="row" style="margin: 0;">
        <% @maraudes.each do |maraude| %>
        <div class="col-6" style="padding: 18px;" id="card">
            <%= link_to maraude_path(maraude) do %>
              <div class="card-trip zoom picture" data-id='<%= maraude.id %>' >
                <%= cl_image_tag maraude.photo %>
                <div class="card-trip-infos">
                  <div>
                    <h2><%= maraude.title %></h2>
                    <p><%= I18n.l(maraude.starts_at, format: :long, locale: :'fr')%></p>
                  </div>
                  <h2><%= maraude.capacity.to_i - maraude.bookings.size %> places</h2>
                  <%= cl_image_tag(maraude.asso.photo, width: 40, height: 40, crop: :fill, class: "avatar-bordered card-trip-user") %>
                </div>
              </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="index-right-part"
      id="map"
          style="width: 604px;
          "
          data-markers="<%= @markers.to_json %>"
          data-markers-actual-position="<%= @markers_actual_position.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/maraudes/show.html.erb
<div class="maraude-show-background" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path(@maraude.photo) %>');">
    <!-- <div class="container-retour" data-aos="fade-up">
      <%#= link_to maraudes_path do %>
        <h3 id="section-retour"><i class="far fa-arrow-alt-circle-left"></i>Retour aux missions</h3>
      <%# end %>
    </div> -->

  <div class="maraude-show-card" style="position: relative;">
    <div class="back-to-maraudes">
      <%= link_to request.referer do %>
        <h3 class="section-retour"><i class="far fa-arrow-alt-circle-left" style="padding-right: 10px;"></i>Retour aux maraudes</h3>
      <% end %>
    </div>
    <div class="maraude-card-left-part">
      <div
        id="map"
        data-markers="<%= @markers.to_json %>"
        data-steps="<%= @steps.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="maraude-card-right-part">
      <div class="maraude-show-description">
        <%= cl_image_tag(@maraude.photo) %>
        <h3><strong><%= @maraude.title %></strong></h3>
        <p><%= @maraude.description %></p>
      </div>
      <div class="maraude-show-details">
        <p style="margin-top: 39px;"><i class="far fa-calendar-alt" style="padding-right: 6px;"></i><strong><%= I18n.l(@maraude.starts_at, format: :long, locale: :'fr')%> / <%= @maraude.ends_at.strftime("%H:%M") %></strong></p>
         <p class="" style="font-weight: 600;"><i class="fas fa-map-marker-alt" style="padding-right: 6px;"></i> départ : <%= @maraude.address_start %></p>
         <p class="" style="font-weight: 600;"><i class="fas fa-flag-checkered" style="padding-right: 6px;"></i> arrivée : <%= @maraude.address_end %></p>
         <p class="mb-5">La demande de <%=@maraude.asso.name %> est de <strong><%= @maraude.capacity %> personnes</strong>.<span style="background-color:#FED137">Il reste <strong> <%= @remaining_places %> </strong> places !</p></span>


         <div class="mt-3">
            <div class="mb-4">
              <p>Organisé par :</p>
              <div class="asso-infos">
               <%= cl_image_tag(@maraude.asso.photo, width: 100, height: 100, crop: :fill, class: "image-bordered") %>
               <div style="padding-left: 10px;">
                <p><%= @maraude.asso.name %></p>
                <p><%= @maraude.asso.address %></p>
                <p><%= @maraude.asso.phone_number %></p>
               </div>
              </div>
            </div>
           <% if user_signed_in? %>
             <% if current_user.bookings.where(maraude: @maraude).exists? %>
               <h3 class="text-center">Vous avez déjà réservé cette maraude </h3>
             <% elsif @remaining_places == 0 %>
               <h2>Il n'y a plus de place</h2>
             <% else %>
               <%= simple_form_for [@maraude, @booking] do |f| %>
                 <div class="d-flex justify-content-center mb-4">
                   <%= f.submit "Participez à cette maraude", class: "btn", style: "background-color: #FFE436; border-radius: 15px; padding: 10px; width: 330px;"%>
                 </div>
               <% end %>
             <% end %>
           <% end %>
         </div>

      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="full" style="position: relative;">
  <div class="d-flex dashboard">
    <div class="nav flex-column nav-pills sidebar border border-light" id="v-pills-tab" role="tablist" aria-orientation="vertical">

      <h4>Alvéole</h4>

       <!-- <div class="avatar-image" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">
        <a><%= image_tag current_user.photo, class: "avatar-large-dashboard" %></a>
      </div> -->


      <!-- <div style="display: flex;height: 58px;"> -->
        <a class="nav-link nav-link-dashboard active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Mes réservations</a>
      <!-- </div> -->

      <!-- <div style="display: flex;height: 58px;"> -->
        <a class="nav-link nav-link-dashboard" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Historique</a>
      <!-- </div> -->

      <% if !@asso.nil?  %>
        <!-- <div style="display: flex;height: 58px;"> -->
          <a class="nav-link nav-link-dashboard" id="v-pills-maraudes-tab" data-toggle="pill" href="#v-pills-maraudes" role="tab" aria-controls="v-pills-maraudes" aria-selected="false">Mes maraudes</a>
        <!-- </div> -->
      <% end %>

         </div>

    <div class="right-part p-3 bg-white rounded">
        <%= link_to " ← Retour aux maraudes", maraudes_path %>
        <div class="tab-content" id="v-pills-tabContent">

          <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <div class="right-part-header">
              <h3>Mes réservations </h3>
            </div>
            <% if @current_bookings == [] %>
              <p>Pas de prochaines réservations 😱. Trouvez votre future maraude disponible :
                <%= link_to "ici", maraudes_path %> </p>
            <% else %>
              <% @current_bookings&.each do |booking| %>
                <div class="card-product-dashboard">
                  <div class="dashboard-activity-image" style="background-image: linear-gradient(rgba(255,255,255,0.6), rgba(255,255,255,0.6)), url(<%= booking.maraude.photo %>)">
                    <p>Débute dans <strong><%= number_of_days(DateTime.now, booking.maraude.starts_at)%></strong> jours </p>
                  </div>
                  <!-- <p>Débute dans <strong><%#= number_of_days(DateTime.now, booking.maraude.starts_at)%></strong> jours </p> -->
                  <!-- <img src="<%= booking.maraude.photo %>" /> -->
                  <div class="card-product-dashboard-infos">
                    <div class="booking-info">
                      <h2><%= booking.maraude.title %></h2>
                      <p><i class="fas fa-map-marker-alt"></i> <%= booking.maraude.address_start %></p>
                      <p> <i class="fas fa-flag-checkered"></i> <%= booking.maraude.address_end%></p>
                      <p class="participe"><i class="fas fa-users"></i> Je participe avec <strong> <%= booking.maraude.remaining_places %></strong> personnes</p>
                    </div>
                    <div class="booking-time">
                      <div>

                          <div><p><%= link_to "Plus d'info", maraude_path(booking.maraude_id), class: 'btn btn-warning booking-btn' %></p></div>
                      </div>
                      <!-- <div class="red"><p><%= booking.maraude.ends_at %></p></div> -->
                    </div>

                  </div>
                </div>
              <% end %>
            <% end %>
        </div>

        <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
          <div class="right-part-header">
            <h3>Toutes les maraudes passées : </h3>
          </div>
            <% if @past_bookings.nil? %>
              <p>Nous avons bien cherché mais n'avons pas trouvé de réservations.</p>
            <% else %>
              <% @past_bookings&.each do |booking| %>
                  <div class="card-product-dashboard">
                    <img src="<%= booking.maraude.photo %>" />
                    <div class="card-product-dashboard-infos">
                      <div class="booking-info">
                        <h2><%= booking.maraude.title %> ✅</h2>
                        <p><i class="fas fa-map-marker-alt"></i> <%= booking.maraude.address_start %></p>
                        <p> <i class="fas fa-flag-checkered"></i> <%= booking.maraude.address_end%></p>
                        <p class="participe"><i class="fas fa-users"></i> J'ai participé avec <strong> <%= booking.maraude.remaining_places %></strong> personnes</p>
                      </div>
                    </div>
                  </div>
                <% end %>
            <% end %>
        </div>

        <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
          <div class="right-part-header">
            <h3>Information du profil</h3>
          </div>
            <p>Prénom</p>
            <%= current_user.first_name %>
            <p>Nom</p>
            <%= current_user.last_name %>
            <p>Email</p>
            <%= current_user.email %>
            <p>Numéro de téléphone</p>
            <%= current_user.phone_number %>
        </div>

        <% if !@asso.nil? %>
          <div class="tab-pane fade" id="v-pills-maraudes" role="tabpanel" aria-labelledby="v-pills-maraudes-tab">
            <!-- <div class="d-flex justify-content-between">
               \
            </div> -->
            <!-- <div class="d-flex justify-content-between"> -->
              <div class="right-part-header">
                <h3>Toutes les maraudes crées</h3>
                <button class="btn btn-warning add-a-maraude">Créer une maraude</button>
              </div>

            <% @maraudes_as_owner.each do |maraude| %>
              <div class="card-product-dashboard maraude-dashboard">
                  <img src="<%= maraude.photo %>" />
                  <div class="card-product-dashboard-infos">
                    <div class="booking-info">
                      <div>
                        <h2><%= maraude.title %></h2>
                        <p><i class="fas fa-map-marker-alt"></i> <%= maraude.address_start %></p>
                        <p> <i class="fas fa-flag-checkered"></i> <%= maraude.address_end%></p>
                        <p> <i class="fas fa-users"></i> <%= maraude.capacity %> </p>
                      </div>
                    </div>
                    <div class="booking-time">
                      <!-- <div> -->
                        <% if number_of_days(DateTime.now, maraude.starts_at) < 0 %>
                          <p> La maraude s'est terminée il y a <strong><%= -number_of_days(DateTime.now, maraude.starts_at)%></strong> jours</p>
                        <% else %>
                          <p>Débute dans <strong><%= number_of_days(DateTime.now, maraude.starts_at)%></strong> jours à <%=maraude.starts_at.strftime("%H:%M")%>
                          le <%= maraude.starts_at.strftime("%d/%m/%Y") %></p>
                        <% end %>
                        <%= link_to "Plus d'info", maraude_path(maraude), class: 'btn btn-warning booking-btn' %>
                      <!-- </div> -->

                    </div>

                  </div>
                </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="sidenav">
    <div class="sidenav-left-part">

    </div>
    <div class="sidenav-right-part">
      <div>
            <h1>Créez votre Maraude</h1>
      <%= simple_form_for Maraude.new, remote: true do |f| %>
        <div>
          <div>
            <div>
              <%= f.input :title, label: "Titre", input_html: { class: "create-style"} %>
            </div>
            <div>
              <%= f.input :description, label: "Description",input_html: { class: "create-style"} %>
            </div>
          </div>
          <div>
            <div>
              <%= f.input :address_start, label: "Adresse Départ",input_html: { class: "create-style autocomplete" }%>
            </div>
            <div>
              <%= f.input :address_end, label: "Adresse Arrivée",input_html: { class: "create-style autocomplete" } %>
            </div>
          </div>
          <div>
            <div>
              <%= f.input :starts_at, label: "Débute le",as: :string, input_html: { id: "starts_at", class: "create-style"} %>
            </div>
            <div>
              <%= f.input :ends_at, label: "Termine le",as: :string, input_html: { id: "ends_at", class: "create-style"} %>
            </div>
          </div>
          <div>
            <div>
              <%= f.input :capacity, label: "Nombre de place",input_html: { class: "create-style"} %>
            </div>
            <div>
            <%= f.input :photo, input_html: { class: "create-style"} %>
            </div>
          </div>
​
        </div>
        <%= f.submit "Valider", class: "cta-validate" %>
      <% end %>
        <div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top a black-nav" id="mainNav">
  <div class="mauraude-navbar">
    <div class="navbar-left">
      <%= link_to root_path, class: "navbar-brand" do %>
        Alveole Paris
      <% end %>

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#service">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#maraude">Maraudes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#equipe">Qui sommes-nous ?</a>
          </li>
          <li class="nav-item">
            <%= link_to "Trouver une maraude", maraudes_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
    <div class="navbar-right">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto" style= "align-items: center">
            <% if user_signed_in? %>

              <li class="nav-item">
                <p style="margin: 0;" class="nav-link <%= "home-nav-item color-black" if params[:controller] == "maraudes" && params[:action] == "index" %>">Bonjour 👋  <%= current_user.first_name %></p>
              </li>
              <li class="nav-item dropdown">
                <% if current_user.assos != [] %>
                <%= image_tag "#{current_user.assos.first.photo}", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else %>
                <%= image_tag "#{current_user.photo}", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Mes maraudes", "/dashboard", class: "dropdown-item #{"home-nav-item color-black" if params[:controller] == "maraudes" && params[:action] == "index"}" %>
                  <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
</nav>